name: 'action-migrations'
description: 'Actions related to django migrations in sentry'
author: 'sentry.io'
inputs:
  cmd:
    required: false
    description: "The command to run to generate SQL"
    default: "sentry django sqlmigrate sentry"
  run:
    required: false
    description: 'Action for the action to take. Possible values: null, "placeholder"'
  name:
    required: false
    description: 'A unique name, required for multiple migrations in a Pull Request'
  migration:
    required: true
    description: 'file name (or number) for the migration'
  githubToken:
    required: false
    default: '${{ github.token }}'
    description: 'GitHub Token (available as `secrets.GITHUB_TOKEN`)'
  rawBody:
    required: false
    default: 'false'
    description: 'When true, use the commands output directly as comment body, interpreting it as markdown.'
runs:
  using: 'node12'
  main: 'dist/index.js'
